### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ThatoMolefe** [reportportal/agent-js-cucumber#26] opened 2019-08-29 08:17 UTC
at Object.reportPortalHandlers (/home/thato/Downloads/agent-js-cucumber-master/modules/cucumber-epam-reportportal-handler.js:183:27)
    at consumer (/home/thato/Downloads/agent-js-cucumber-master/testSample/features/step_definitions/support/handlers.js:8:30)
    at /home/thato/Downloads/agent-js-cucumber-master/node_modules/cucumber/lib/support_code_library/builder.js:77:12
    at Array.forEach (<anonymous>)
    at Object.build (/home/thato/Downloads/agent-js-cucumber-master/node_modules/cucumber/lib/support_code_library/builder.js:76:7)
    at Cli.getSupportCodeLibrary (/home/thato/Downloads/agent-js-cucumber-master/node_modules/cucumber/lib/cli/index.js:137:32)
    at /home/thato/Downloads/agent-js-cucumber-master/node_modules/cucumber-parallel/lib/cucumber/cucumber_js.js:157:42
    at tryCatcher (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/thato/Downloads/agent-js-cucumber-master/node_modules/bluebird/js/release/async.js:17:14)

**Comment by sujithshajee** [comment] 2019-10-21 18:26
was there a resolution for identified for this issues.

**Comment by Viru1988** [comment] 2019-11-23 22:26
I am facing the same issue as well

**Comment by AmsterGet** [comment] 2020-08-13 08:57
Closed as a duplicate of https://github.com/reportportal/agent-js-cucumber/issues/23

**Closed by AmsterGet** 2020-08-13 08:57 UTC
