### ISSUE TITLE
Launch is not finished in report portal for the example scenario given

### ISSUE THREAD

**Issue by saravanan-autodev** [reportportal/agent-js-cucumber#48] opened 2020-05-18 19:45 UTC
When i tried to execute the example scenario provided in the master branch, I am getting the below error and launch is not finished at report portal end and in the console the scenario got failed.

![image](https://user-images.githubusercontent.com/62570501/82253081-40981a00-991e-11ea-9052-895da70b8a2a.png)

How can we run this scripts using protractor command. When i tried to executed through protractor.conf.js (I prepared ) i was getting error and I was not able to run the sample scenario.
Can you let me know the steps to run this using protractor

**Comment by AmsterGet** [comment] 2020-10-25 20:51
Hi @saravanan-autodev !
Have you had the opportunity to use our latest ʻ@reportportal/agent-js-cucumber`?

**Comment by KatsiarynaTatarynovich** [comment] 2020-11-23 08:33
We have closed this issue. If the problem is still valid, be free to reopen it

**Closed by KatsiarynaTatarynovich** 2020-11-23 08:33 UTC
